name: newtook
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  animated_snack_bar: ^0.3.0
  authentication_repository:
    path: packages/authentication_repository
  auto_route: ^5.0.1
  country_icons: ^2.0.2
  cryptlib_2_0: ^0.0.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_analytics: ^9.3.5
  firebase_core: ^1.22.0
  firebase_crashlytics: ^2.8.10
  firebase_messaging: ^13.0.2
  firebase_performance: ^0.8.3
  firebase_remote_config: ^2.0.17
  flutter:
    sdk: flutter
  flutter_awesome_buttons: ^1.1.0
  flutter_bloc: ^8.1.1
  flutter_local_notifications: ^11.0.1
  flutter_localizations:
    sdk: flutter
  flutter_services_binding: null
  formz: ^0.4.0
  geolocator: ^9.0.2
  google_fonts: ^3.0.1
  graphql_flutter: ^5.1.0
  hex: ^0.2.0
  http: ^0.13.5
  hydrated_bloc: ^9.0.0-dev.3
  intl: ^0.17.0
  intl_phone_number_input: ^0.7.1
  load_switch: ^1.1.0
  path_provider: ^2.0.11
  persistent_bottom_nav_bar: ^5.0.2
  pin_code_fields: ^7.4.0
  provider: ^6.0.3
  qr_code_scanner: ^1.0.1
  rounded_loading_button: ^2.1.0
  sms_autofill: ^2.2.0
  top_snackbar_flutter: ^2.1.1
  user_repository:
    path: packages/user_repository
  workmanager: ^0.5.0

dev_dependencies:
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
