// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu4_6ZtApKGHNcl0PXORFyL42FGLHMeOQ',
    appId: '1:92327347967:web:bfd7661dcda7e82e16eeca',
    messagingSenderId: '92327347967',
    projectId: 'arryt-b201e',
    authDomain: 'arryt-b201e.firebaseapp.com',
    storageBucket: 'arryt-b201e.appspot.com',
    measurementId: 'G-XS9YZJKWTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz5DeoDqhOQuO2e3g2rp40TYo-vSItZHE',
    appId: '1:92327347967:android:a81e5e2848167b0816eeca',
    messagingSenderId: '92327347967',
    projectId: 'arryt-b201e',
    storageBucket: 'arryt-b201e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCab4NKp6oGydeA_J9Dk5kUNHU6RkLc16Y',
    appId: '1:92327347967:ios:015a27a2b457e55216eeca',
    messagingSenderId: '92327347967',
    projectId: 'arryt-b201e',
    storageBucket: 'arryt-b201e.appspot.com',
    iosClientId: '92327347967-i90lg2brvpj5do6u2u8737phetfh5f8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.newtook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCab4NKp6oGydeA_J9Dk5kUNHU6RkLc16Y',
    appId: '1:92327347967:ios:015a27a2b457e55216eeca',
    messagingSenderId: '92327347967',
    projectId: 'arryt-b201e',
    storageBucket: 'arryt-b201e.appspot.com',
    iosClientId: '92327347967-i90lg2brvpj5do6u2u8737phetfh5f8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.newtook',
  );
}
